OpenSSH-74
Imported from OpenSSH-74.tar.gz

diff --git a/patches/EA.patch b/patches/EA.patch
--- a/patches/EA.patch
+++ b/patches/EA.patch
@@ -1,19 +1,304 @@
-diff -u --exclude=CVS -r -udbp configure.ac configure.ac
---- configure.ac	2004-04-16 20:03:07.000000000 -0700
-+++ configure.ac	2005-02-21 18:46:25.000000000 -0800
-@@ -2869,6 +2869,9 @@ if test "$ac_cv_lib_pam_pam_set_item" = 
- 	LIBS=`echo $LIBS | sed 's/-ldl //'`
- fi
+diff -Naur ../openssh-4.4p1.orig/config.h.in ./config.h.in
+--- ../openssh-4.4p1.orig/config.h.in	2006-09-26 04:03:33.000000000 -0700
++++ ./config.h.in	2006-10-19 17:37:13.000000000 -0700
+@@ -56,6 +56,18 @@
+ /* Define if your snprintf is busted */
+ #undef BROKEN_SNPRINTF
+ 
++/* platform uses an in-memory credentials cache */
++#undef USE_CCAPI
++
++/* platform has a Security Authorization Session API */
++#undef USE_SECURITY_SESSION_API
++
++/* Define to 1 if you have the `copyfile' function. */
++#undef HAVE_COPYFILE
++
++/* Define to 1 if you have the <copyfile.h> header file. */
++#undef HAVE_COPYFILE_H
++
+ /* updwtmpx is broken (if present) */
+ #undef BROKEN_UPDWTMPX
+ 
+diff -Naur ../openssh-4.4p1.orig/configure ./configure
+--- ../openssh-4.4p1.orig/configure	2006-09-26 04:03:41.000000000 -0700
++++ ./configure	2006-10-19 17:42:00.000000000 -0700
+@@ -32166,6 +32166,259 @@
+ CFLAGS="$CFLAGS $werror_flags"
+ 
+ 
++for ac_func in copyfile
++do
++as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
++echo "$as_me:$LINENO: checking for $ac_func" >&5
++echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
++if eval "test \"\${$as_ac_var+set}\" = set"; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
++   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
++#define $ac_func innocuous_$ac_func
++
++/* System header to define __stub macros and hopefully few prototypes,
++    which can conflict with char $ac_func (); below.
++    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
++    <limits.h> exists even on freestanding compilers.  */
++
++#ifdef __STDC__
++# include <limits.h>
++#else
++# include <assert.h>
++#endif
++
++#undef $ac_func
++
++/* Override any gcc2 internal prototype to avoid an error.  */
++#ifdef __cplusplus
++extern "C"
++{
++#endif
++/* We use char because int might match the return type of a gcc2
++   builtin and then its argument prototype would still apply.  */
++char $ac_func ();
++/* The GNU C library defines this for functions which it implements
++    to always fail with ENOSYS.  Some functions are actually named
++    something starting with __ and the normal name is an alias.  */
++#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
++choke me
++#else
++char (*f) () = $ac_func;
++#endif
++#ifdef __cplusplus
++}
++#endif
++
++int
++main ()
++{
++return f != $ac_func;
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
++  (eval $ac_link) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag"
++			 || test ! -s conftest.err'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest$ac_exeext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  eval "$as_ac_var=yes"
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++eval "$as_ac_var=no"
++fi
++rm -f conftest.err conftest.$ac_objext \
++      conftest$ac_exeext conftest.$ac_ext
++fi
++echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
++echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
++if test `eval echo '${'$as_ac_var'}'` = yes; then
++  cat >>confdefs.h <<_ACEOF
++#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
++_ACEOF
++
++fi
++done
++
++
++for ac_header in copyfile.h
++do
++as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
++if eval "test \"\${$as_ac_Header+set}\" = set"; then
++  echo "$as_me:$LINENO: checking for $ac_header" >&5
++echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
++if eval "test \"\${$as_ac_Header+set}\" = set"; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++fi
++echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
++echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
++else
++  # Is the header compilable?
++echo "$as_me:$LINENO: checking $ac_header usability" >&5
++echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++$ac_includes_default
++#include <$ac_header>
++_ACEOF
++rm -f conftest.$ac_objext
++if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
++  (eval $ac_compile) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag"
++			 || test ! -s conftest.err'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest.$ac_objext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_header_compiler=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_header_compiler=no
++fi
++rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
++echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
++echo "${ECHO_T}$ac_header_compiler" >&6
++
++# Is the header present?
++echo "$as_me:$LINENO: checking $ac_header presence" >&5
++echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++#include <$ac_header>
++_ACEOF
++if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
++  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } >/dev/null; then
++  if test -s conftest.err; then
++    ac_cpp_err=$ac_c_preproc_warn_flag
++    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
++  else
++    ac_cpp_err=
++  fi
++else
++  ac_cpp_err=yes
++fi
++if test -z "$ac_cpp_err"; then
++  ac_header_preproc=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++  ac_header_preproc=no
++fi
++rm -f conftest.err conftest.$ac_ext
++echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
++echo "${ECHO_T}$ac_header_preproc" >&6
++
++# So?  What about this header?
++case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
++  yes:no: )
++    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
++echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
++    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
++echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
++    ac_header_preproc=yes
++    ;;
++  no:yes:* )
++    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
++echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
++    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
++echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
++echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
++    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
++echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
++    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
++echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
++echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
++    (
++      cat <<\_ASBOX
++## ------------------------------------------- ##
++## Report this to openssh-unix-dev@mindrot.org ##
++## ------------------------------------------- ##
++_ASBOX
++    ) |
++      sed "s/^/$as_me: WARNING:     /" >&2
++    ;;
++esac
++echo "$as_me:$LINENO: checking for $ac_header" >&5
++echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
++if eval "test \"\${$as_ac_Header+set}\" = set"; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  eval "$as_ac_Header=\$ac_header_preproc"
++fi
++echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
++echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
++
++fi
++if test `eval echo '${'$as_ac_Header'}'` = yes; then
++  cat >>confdefs.h <<_ACEOF
++#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
++_ACEOF
++
++fi
++
++done
++
++
++
+ ac_config_files="$ac_config_files Makefile buildpkg.sh opensshd.init openssh.xml openbsd-compat/Makefile openbsd-compat/regress/Makefile scard/Makefile ssh_prng_cmds survey.sh"
+ 
+ cat >confcache <<\_ACEOF
+diff -Naur ../openssh-4.4p1.orig/configure.ac ./configure.ac
+--- ../openssh-4.4p1.orig/configure.ac	2006-09-24 12:08:59.000000000 -0700
++++ ./configure.ac	2006-10-19 17:42:56.000000000 -0700
+@@ -3916,6 +3916,9 @@
+ dnl Add now.
+ CFLAGS="$CFLAGS $werror_flags"
  
 +AC_CHECK_FUNCS(copyfile)
 +AC_CHECK_HEADERS(copyfile.h)
 +
  AC_EXEEXT
- AC_CONFIG_FILES([Makefile openbsd-compat/Makefile scard/Makefile ssh_prng_cmds])
- AC_OUTPUT
-diff -u --exclude=CVS -r -udbp scp.1 scp.1
---- scp.1	2004-03-08 04:12:36.000000000 -0800
-+++ scp.1	2005-02-21 18:46:25.000000000 -0800
+ AC_CONFIG_FILES([Makefile buildpkg.sh opensshd.init openssh.xml \
+ 	openbsd-compat/Makefile openbsd-compat/regress/Makefile \
+diff -Naur ../openssh-4.4p1.orig/scp.1 ./scp.1
+--- ../openssh-4.4p1.orig/scp.1	2006-07-23 21:04:36.000000000 -0700
++++ ./scp.1	2006-10-19 17:43:58.000000000 -0700
 @@ -20,7 +20,7 @@
  .Sh SYNOPSIS
  .Nm scp
@@ -23,7 +308,7 @@ diff -u --exclude=CVS -r -udbp scp.1 scp.1
  .Op Fl c Ar cipher
  .Op Fl F Ar ssh_config
  .Op Fl i Ar identity_file
-@@ -87,6 +87,8 @@ Passes the
+@@ -87,6 +87,8 @@
  flag to
  .Xr ssh 1
  to enable compression.
@@ -32,10 +317,10 @@ diff -u --exclude=CVS -r -udbp scp.1 scp.1
  .It Fl c Ar cipher
  Selects the cipher to use for encrypting the data transfer.
  This option is directly passed to
-diff -u --exclude=CVS -r -udbp scp.c scp.c
---- scp.c	2003-11-23 18:09:28.000000000 -0800
-+++ scp.c	2005-02-21 18:46:52.000000000 -0800
-@@ -80,6 +80,11 @@ RCSID("$OpenBSD: scp.c,v 1.113 2003/11/2
+diff -Naur ../openssh-4.4p1.orig/scp.c ./scp.c
+--- ../openssh-4.4p1.orig/scp.c	2006-08-04 19:39:40.000000000 -0700
++++ ./scp.c	2006-10-19 18:06:48.000000000 -0700
+@@ -104,6 +104,11 @@
  #include "misc.h"
  #include "progressmeter.h"
  
@@ -44,10 +329,10 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
 +#include <copyfile.h>
 +#endif
 +
- #ifdef HAVE___PROGNAME
  extern char *__progname;
- #else
-@@ -109,6 +114,12 @@ char *ssh_program = _PATH_SSH_PROGRAM;
+ 
+ int do_cmd(char *host, char *remuser, char *cmd, int *fdin, int *fdout);
+@@ -131,6 +136,12 @@
  /* This is used to store the pid of ssh_program */
  pid_t do_cmd_pid = -1;
  
@@ -60,7 +345,7 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
  static void
  killchild(int signo)
  {
-@@ -231,7 +242,11 @@ main(int argc, char **argv)
+@@ -310,7 +321,11 @@
  	addargs(&args, "-oClearAllForwardings yes");
  
  	fflag = tflag = 0;
@@ -72,7 +357,7 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
  		switch (ch) {
  		/* User-visible flags. */
  		case '1':
-@@ -277,6 +292,11 @@ main(int argc, char **argv)
+@@ -356,6 +371,11 @@
  			showprogress = 0;
  			break;
  
@@ -84,7 +369,7 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
  		/* Server options. */
  		case 'd':
  			targetshouldbedirectory = 1;
-@@ -326,7 +346,12 @@ main(int argc, char **argv)
+@@ -405,7 +425,12 @@
  	remin = remout = -1;
  	do_cmd_pid = -1;
  	/* Command to be executed on remote system using "ssh". */
@@ -97,19 +382,18 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
  	    verbose_mode ? " -v" : "",
  	    iamrecursive ? " -r" : "", pflag ? " -p" : "",
  	    targetshouldbedirectory ? " -d" : "");
-@@ -507,6 +532,11 @@ source(int argc, char **argv)
- 	int fd, haderr, indx;
+@@ -584,6 +609,10 @@
+ 	int fd = -1, haderr, indx;
  	char *last, *name, buf[2048];
  	int len;
 +#if HAVE_COPYFILE
 +	char md_name[MAXPATHLEN];
 +	char *md_tmp;
 +#endif
-+
  
  	for (indx = 0; indx < argc; ++indx) {
  		name = argv[indx];
-@@ -519,6 +549,17 @@ source(int argc, char **argv)
+@@ -596,6 +625,17 @@
  			    name);
  			goto next;
  		}
@@ -127,7 +411,7 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
  		if ((fd = open(name, O_RDONLY, 0)) < 0)
  			goto syserr;
  		if (fstat(fd, &stb) < 0) {
-@@ -602,6 +643,36 @@ next:			(void) close(fd);
+@@ -685,6 +725,36 @@
  		else
  			run_err("%s: %s", name, strerror(haderr));
  		(void) response();
@@ -164,7 +448,7 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
  	}
  }
  
-@@ -748,6 +819,10 @@ sink(int argc, char **argv)
+@@ -833,6 +903,10 @@
  	if (stat(targ, &stb) == 0 && S_ISDIR(stb.st_mode))
  		targisdir = 1;
  	for (first = 1;; first = 0) {
@@ -173,9 +457,9 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
 +		char md_dst[MAXPATHLEN];
 +#endif
  		cp = buf;
- 		if (atomicio(read, remin, cp, 1) <= 0)
+ 		if (atomicio(read, remin, cp, 1) != 1)
  			return;
-@@ -873,6 +948,29 @@ sink(int argc, char **argv)
+@@ -966,6 +1040,29 @@
  		}
  		omode = mode;
  		mode |= S_IWRITE;
@@ -205,7 +489,7 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
  		if ((ofd = open(np, O_WRONLY|O_CREAT, mode)) < 0) {
  bad:			run_err("%s: %s", np, strerror(errno));
  			continue;
-@@ -959,6 +1057,21 @@ bad:			run_err("%s: %s", np, strerror(er
+@@ -1053,6 +1150,21 @@
  			wrerrno = errno;
  		}
  		(void) response();
@@ -227,7 +511,7 @@ diff -u --exclude=CVS -r -udbp scp.c scp.c
  		if (setimes && wrerr == NO) {
  			setimes = 0;
  			if (utimes(np, tv) < 0) {
-@@ -1020,7 +1133,11 @@ void
+@@ -1114,7 +1226,11 @@
  usage(void)
  {
  	(void) fprintf(stderr,
